---
- name: Install apache2 and upload my webpage
  hosts: 192.168.88.103
  become: yes

  vars:
    source_file: ./copy/index.html
    destin_file: /var/www/html/

  tasks:
  - name: install apache2
    apt: name=apache2 state=latest

  - name: Copy index.html to server
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    notify: Restart Apache2

  - name: Start webserver and make it enable on boot
    service: name=apache2 state=started enabled=yes
    
  handlers:
  - name: Restart Apache2
    service: name=apache2 state=restarted
